/**
 * PALETAS CURADAS + SOPORTE CUSTOM — 30 curadas + custom (31 total)
 * Cada paleta define 7 tokens base que alimentan @theme.
 * Si palette === "custom", se usan theme.colors del siteConfig.
 */

export const PALETTES = Object.freeze([
  "forest",
  "denim-orange",
  "earth",
  "ocean",
  "sunset",
  "graphite",
  "wine",
  "midnight",
  "sand",
  "sage",
  "terracotta",
  "mustard",
  "plum",
  "teal",
  "coral",
  "slate",
  "amber",
  "olive",
  "berry",
  "sky",
  "mint",
  "lavender",
  "charcoal",
  "sandstone",
  "clay",
  "moss",
  "dusk",
  "pepper",
  "honey",
  "indigo",
  "forest-dark",
  "denim-orange-dark",
  "earth-dark",
  "ocean-dark",
  "sunset-dark",
  "graphite-dark",
  "wine-dark",
  "midnight-dark",
  "sand-dark",
  "sage-dark",
  "terracotta-dark",
  "mustard-dark",
  "plum-dark",
  "teal-dark",
  "coral-dark",
  "slate-dark",
  "amber-dark",
  "olive-dark",
  "berry-dark",
  "sky-dark",
  "mint-dark",
  "lavender-dark",
  "charcoal-dark",
  "sandstone-dark",
  "clay-dark",
  "moss-dark",
  "dusk-dark",
  "pepper-dark",
  "honey-dark",
  "indigo-dark",
  "sage-pastel",
  "mint-pastel",
  "lavender-pastel",
  "sky-pastel",
  "peach-pastel",
  "butter-pastel",
  "rose-pastel",
  "clay-pastel",
  "sand-pastel",
  "dusk-pastel",
  "teal-pastel",
  "moss-pastel",
  "slate-pastel",
  "indigo-pastel",
  "strawberry-pastel",
  "custom",
]);

// Paletas curadas — hex verificados para contraste AA
export const PALETTE_DEFINITIONS = Object.freeze({
  forest: {
    label: "Bosque",
    description: "Verde profundo + dorado — elegante y natural.",
    colors: {
      ink: "#172033",
      muted: "#5f6878",
      surface: "#faf8f3",
      surfaceAlt: "#eef1f5",
      brand: "#234f46",
      brandDark: "#17372f",
      accent: "#d39b46",
    },
  },
  "denim-orange": {
    label: "Denim Naranja",
    description: "Azul jean + naranja — vibrante y juvenil (J&M).",
    colors: {
      ink: "#10243a",
      muted: "#607184",
      surface: "#f5f6f7",
      surfaceAlt: "#e7ebef",
      brand: "#17456d",
      brandDark: "#0c2844",
      accent: "#f47a20",
    },
  },
  earth: {
    label: "Tierra",
    description: "Marrón café + caramelo — ideal cafetalero.",
    colors: {
      ink: "#2b1d14",
      muted: "#7a6a5f",
      surface: "#fdf8f0",
      surfaceAlt: "#f0e6d8",
      brand: "#5c3d2e",
      brandDark: "#3d281e",
      accent: "#c49a6c",
    },
  },
  ocean: {
    label: "Océano",
    description: "Teal profundo + aqua — fresco y confiable.",
    colors: {
      ink: "#0f2a2e",
      muted: "#5a6e71",
      surface: "#f0f7f4",
      surfaceAlt: "#dceee8",
      brand: "#0e4d4e",
      brandDark: "#0a3636",
      accent: "#2ec4b6",
    },
  },
  sunset: {
    label: "Atardecer",
    description: "Vino + naranja cálido — acogedor y gourmet.",
    colors: {
      ink: "#2e1a1a",
      muted: "#7a5f5f",
      surface: "#fdf5f0",
      surfaceAlt: "#f5e0d3",
      brand: "#7a2e2e",
      brandDark: "#5a1f1f",
      accent: "#ff8c42",
    },
  },
  graphite: {
    label: "Grafito",
    description: "Gris azulado + acero — minimal tech.",
    colors: {
      ink: "#1a1d2e",
      muted: "#6b7280",
      surface: "#f8f9fb",
      surfaceAlt: "#e8eaef",
      brand: "#2b2d42",
      brandDark: "#1a1c2e",
      accent: "#8d99ae",
    },
  },
  wine: {
    label: "Vino",
    description: "Burdeos + dorado suave — premium y artesanal.",
    colors: {
      ink: "#2e1a22",
      muted: "#7a5f6a",
      surface: "#fdf6f0",
      surfaceAlt: "#f0e0d8",
      brand: "#4a1a2f",
      brandDark: "#2e1020",
      accent: "#d4a373",
    },
  },
  midnight: {
    label: "Medianoche",
    description: "Azul noche + celeste — moderno y nocturno.",
    colors: {
      ink: "#0f172a",
      muted: "#64748b",
      surface: "#f1f5f9",
      surfaceAlt: "#e2e8f0",
      brand: "#1e3a5f",
      brandDark: "#0f2340",
      accent: "#38bdf8",
    },
  },
  sand: {
    label: "Arena",
    description: "Beige cálido + terracota — natural y suave.",
    colors: {
      ink: "#2e2a22",
      muted: "#7a7066",
      surface: "#fdfbf7",
      surfaceAlt: "#f5ebe0",
      brand: "#8b5e3c",
      brandDark: "#6b4628",
      accent: "#d6a682",
    },
  },
  sage: {
    label: "Salvia",
    description: "Verde salvia + niebla — orgánico suave.",
    colors: {
      ink: "#1a2e1e",
      muted: "#5a6d5a",
      surface: "#f5f7f3",
      surfaceAlt: "#e8ede8",
      brand: "#5a7a5a",
      brandDark: "#3d5a3d",
      accent: "#a8c69f",
    },
  },
  terracotta: {
    label: "Terracota",
    description: "Barro rojizo + arena — cálido cafetalero.",
    colors: {
      ink: "#2e1a12",
      muted: "#7a5a4a",
      surface: "#fdf6f0",
      surfaceAlt: "#f5e6d8",
      brand: "#c45a3c",
      brandDark: "#8b3d28",
      accent: "#e8a87c",
    },
  },
  mustard: {
    label: "Mostaza",
    description: "Mostaza + carbón — vibrante mostaza.",
    colors: {
      ink: "#2e2a12",
      muted: "#7a7060",
      surface: "#fdfbf0",
      surfaceAlt: "#f5ecd8",
      brand: "#b5892e",
      brandDark: "#8a6a20",
      accent: "#f5d547",
    },
  },
  plum: {
    label: "Ciruela",
    description: "Ciruela + lila — femenino startup.",
    colors: {
      ink: "#2e1a2e",
      muted: "#7a5a7a",
      surface: "#fdf5f9",
      surfaceAlt: "#f0e0ec",
      brand: "#6b2e5a",
      brandDark: "#4a1f3f",
      accent: "#c49ac6",
    },
  },
  teal: {
    label: "Teal",
    description: "Teal profundo + menta — ocean profundo.",
    colors: {
      ink: "#0f2e2e",
      muted: "#5a7a7a",
      surface: "#f0f9f8",
      surfaceAlt: "#dceee8",
      brand: "#0e7a7a",
      brandDark: "#0a5a5a",
      accent: "#2ec4b6",
    },
  },
  coral: {
    label: "Coral",
    description: "Coral + crema — sunset v2.",
    colors: {
      ink: "#2e1a14",
      muted: "#7a5a5a",
      surface: "#fdf5f0",
      surfaceAlt: "#f5e0d8",
      brand: "#e85d4d",
      brandDark: "#b93d2e",
      accent: "#ff8c61",
    },
  },
  slate: {
    label: "Pizarra",
    description: "Pizarra + niebla — minimal graphite v2.",
    colors: {
      ink: "#1a202c",
      muted: "#718096",
      surface: "#f7fafc",
      surfaceAlt: "#edf2f7",
      brand: "#2d3748",
      brandDark: "#1a202c",
      accent: "#a0aec0",
    },
  },
  amber: {
    label: "Ámbar",
    description: "Ámbar + miel — marketplace.",
    colors: {
      ink: "#2e240a",
      muted: "#7a6a3a",
      surface: "#fffbeb",
      surfaceAlt: "#fef3c7",
      brand: "#d97706",
      brandDark: "#92400e",
      accent: "#f59e0b",
    },
  },
  olive: {
    label: "Oliva",
    description: "Oliva + crema — eco.",
    colors: {
      ink: "#1f2e1a",
      muted: "#5a6d4a",
      surface: "#f7f5f0",
      surfaceAlt: "#e8edd8",
      brand: "#5a7a2e",
      brandDark: "#3d5a1e",
      accent: "#8a9a5a",
    },
  },
  berry: {
    label: "Berry",
    description: "Baya + rosa — luxury wine alt.",
    colors: {
      ink: "#2e121a",
      muted: "#7a4a5a",
      surface: "#fdf2f5",
      surfaceAlt: "#f5dce6",
      brand: "#9b2e4a",
      brandDark: "#6b1f33",
      accent: "#d46b8a",
    },
  },
  sky: {
    label: "Cielo",
    description: "Cielo + niebla — corporate.",
    colors: {
      ink: "#0f1f3a",
      muted: "#5a6d8a",
      surface: "#f0f7ff",
      surfaceAlt: "#dce8ff",
      brand: "#1e5a8a",
      brandDark: "#0f3a5a",
      accent: "#38bdf8",
    },
  },
  mint: {
    label: "Menta",
    description: "Menta + crema — fresh.",
    colors: {
      ink: "#0f2e1f",
      muted: "#5a7a65",
      surface: "#f0fdf4",
      surfaceAlt: "#dcfce7",
      brand: "#0e7a4a",
      brandDark: "#065a33",
      accent: "#22c55e",
    },
  },
  lavender: {
    label: "Lavanda",
    description: "Lavanda + niebla — editorial.",
    colors: {
      ink: "#1e1a2e",
      muted: "#6a5a7a",
      surface: "#f5f3ff",
      surfaceAlt: "#ede9fe",
      brand: "#5a3d8b",
      brandDark: "#3d2a5a",
      accent: "#8b5cf6",
    },
  },
  charcoal: {
    label: "Carbón",
    description: "Carbón + niebla — brutalist.",
    colors: {
      ink: "#0f0f0f",
      muted: "#6b7280",
      surface: "#fafafa",
      surfaceAlt: "#f3f4f6",
      brand: "#171717",
      brandDark: "#0a0a0a",
      accent: "#525252",
    },
  },
  sandstone: {
    label: "Arenisca",
    description: "Arenisca + crema — handmade.",
    colors: {
      ink: "#2e241a",
      muted: "#7a6a5a",
      surface: "#fdf8f0",
      surfaceAlt: "#f5ecd8",
      brand: "#8b6a3d",
      brandDark: "#5a4a28",
      accent: "#c9a86a",
    },
  },
  clay: {
    label: "Arcilla",
    description: "Arcilla + niebla — clay extruido.",
    colors: {
      ink: "#2e1e14",
      muted: "#7a5a4a",
      surface: "#fdf6f0",
      surfaceAlt: "#f5e8d8",
      brand: "#b56a3c",
      brandDark: "#8a4a20",
      accent: "#e8a87c",
    },
  },
  moss: {
    label: "Musgo",
    description: "Musgo + piedra — bosque profundo.",
    colors: {
      ink: "#1a2e1a",
      muted: "#5a6d5a",
      surface: "#f5f7f5",
      surfaceAlt: "#e0e8d8",
      brand: "#3d5a3d",
      brandDark: "#1e3d1e",
      accent: "#7a9a5a",
    },
  },
  dusk: {
    label: "Anochecer",
    description: "Anochecer + polvo — dusk suave.",
    colors: {
      ink: "#1e1a2e",
      muted: "#6a5a6d",
      surface: "#f9f5ff",
      surfaceAlt: "#ede5f5",
      brand: "#5a3d6a",
      brandDark: "#3d2a4a",
      accent: "#c49ac6",
    },
  },
  pepper: {
    label: "Pimienta",
    description: "Pimienta + crema — picante editorial.",
    colors: {
      ink: "#1f1410",
      muted: "#7a5a4a",
      surface: "#fdf8f0",
      surfaceAlt: "#f0e6d8",
      brand: "#7a2e1e",
      brandDark: "#5a1f14",
      accent: "#ff6b35",
    },
  },
  honey: {
    label: "Miel",
    description: "Miel + carbón — dulce y dorado.",
    colors: {
      ink: "#2e2410",
      muted: "#7a6a3a",
      surface: "#fffbeb",
      surfaceAlt: "#fef3c7",
      brand: "#b5892e",
      brandDark: "#7a5a20",
      accent: "#f5d547",
    },
  },
  indigo: {
    label: "Índigo",
    description: "Índigo + lavanda — nocturno profundo.",
    colors: {
      ink: "#1a1a2e",
      muted: "#5a5a7a",
      surface: "#f5f3ff",
      surfaceAlt: "#e0e0f5",
      brand: "#3d2e7a",
      brandDark: "#1e1a4a",
      accent: "#6366f1",
    },
  },
  "forest-dark": {
    label: "Bosque Noche",
    description: "Verde profundo noche — oscuro elegante.",
    colors: {
      ink: "#f1f5f9",
      muted: "#94a3b8",
      surface: "#0f1a18",
      surfaceAlt: "#1c2a27",
      brand: "#5fb6a3",
      brandDark: "#3d9a87",
      accent: "#f0c27a",
    },
  },
  "denim-orange-dark": {
    label: "Denim Noche",
    description: "Azul jean noche + naranja.",
    colors: {
      ink: "#f5f6f7",
      muted: "#a0aec0",
      surface: "#0c1a2e",
      surfaceAlt: "#10243a",
      brand: "#5a9bd6",
      brandDark: "#3a6ea5",
      accent: "#ffb86b",
    },
  },
  "earth-dark": {
    label: "Tierra Noche",
    description: "Marrón café noche.",
    colors: {
      ink: "#fdf8f0",
      muted: "#a89985",
      surface: "#1a120e",
      surfaceAlt: "#2b1d14",
      brand: "#c49a6c",
      brandDark: "#8b5e3c",
      accent: "#f0d0a8",
    },
  },
  "ocean-dark": {
    label: "Océano Noche",
    description: "Teal noche.",
    colors: {
      ink: "#f0f7f4",
      muted: "#8ecac6",
      surface: "#0a1a1c",
      surfaceAlt: "#0f2a2e",
      brand: "#4db6b0",
      brandDark: "#2ec4b6",
      accent: "#7dd8d0",
    },
  },
  "sunset-dark": {
    label: "Atardecer Noche",
    description: "Vino noche.",
    colors: {
      ink: "#fdf5f0",
      muted: "#c9a9a0",
      surface: "#1a0f0f",
      surfaceAlt: "#2e1a1a",
      brand: "#e85d4d",
      brandDark: "#c45a3c",
      accent: "#ffb38a",
    },
  },
  "graphite-dark": {
    label: "Grafito Noche",
    description: "Gris noche.",
    colors: {
      ink: "#f8f9fb",
      muted: "#a0aec0",
      surface: "#0f1420",
      surfaceAlt: "#1a1d2e",
      brand: "#8d99ae",
      brandDark: "#6b7280",
      accent: "#c9d1e0",
    },
  },
  "wine-dark": {
    label: "Vino Noche",
    description: "Burdeos noche.",
    colors: {
      ink: "#fdf6f0",
      muted: "#c9a9b8",
      surface: "#1a0f14",
      surfaceAlt: "#2e1a22",
      brand: "#d98fb0",
      brandDark: "#b56a8a",
      accent: "#f0c9a8",
    },
  },
  "midnight-dark": {
    label: "Medianoche Oscura",
    description: "Azul noche profunda.",
    colors: {
      ink: "#f1f5f9",
      muted: "#94a3b8",
      surface: "#020617",
      surfaceAlt: "#0f172a",
      brand: "#38bdf8",
      brandDark: "#0ea5e9",
      accent: "#7dd3fc",
    },
  },
  "sand-dark": {
    label: "Arena Noche",
    description: "Arena noche.",
    colors: {
      ink: "#fdfbf7",
      muted: "#a89f91",
      surface: "#1a1816",
      surfaceAlt: "#2e2a22",
      brand: "#d6a682",
      brandDark: "#a67c52",
      accent: "#f0d0a8",
    },
  },
  "sage-dark": {
    label: "Salvia Noche",
    description: "Salvia noche.",
    colors: {
      ink: "#f5f7f3",
      muted: "#a8b5a8",
      surface: "#0f1f12",
      surfaceAlt: "#1a2e1e",
      brand: "#8bc48a",
      brandDark: "#5a7a5a",
      accent: "#c5e8c0",
    },
  },
  "terracotta-dark": {
    label: "Terracota Noche",
    description: "Terracota noche.",
    colors: {
      ink: "#fdf6f0",
      muted: "#c9a99a",
      surface: "#1a0f0a",
      surfaceAlt: "#2e1a12",
      brand: "#e8a87c",
      brandDark: "#c45a3c",
      accent: "#f5c9a8",
    },
  },
  "mustard-dark": {
    label: "Mostaza Noche",
    description: "Mostaza noche.",
    colors: {
      ink: "#fdfbf0",
      muted: "#c9b896",
      surface: "#1a160a",
      surfaceAlt: "#2e2a12",
      brand: "#f5d547",
      brandDark: "#b5892e",
      accent: "#ffe066",
    },
  },
  "plum-dark": {
    label: "Ciruela Noche",
    description: "Ciruela noche.",
    colors: {
      ink: "#fdf5f9",
      muted: "#c9a9c6",
      surface: "#1a0f1a",
      surfaceAlt: "#2e1a2e",
      brand: "#c49ac6",
      brandDark: "#8a6a9a",
      accent: "#e8c4e6",
    },
  },
  "teal-dark": {
    label: "Teal Noche",
    description: "Teal noche.",
    colors: {
      ink: "#f0f9f8",
      muted: "#8ecac6",
      surface: "#0a1f1f",
      surfaceAlt: "#0f2e2e",
      brand: "#2ec4b6",
      brandDark: "#0e7a7a",
      accent: "#7dd8d0",
    },
  },
  "coral-dark": {
    label: "Coral Noche",
    description: "Coral noche.",
    colors: {
      ink: "#fdf5f0",
      muted: "#c9a9a0",
      surface: "#1a0f0a",
      surfaceAlt: "#2e1a14",
      brand: "#ff8c61",
      brandDark: "#e85d4d",
      accent: "#ffb38a",
    },
  },
  "slate-dark": {
    label: "Pizarra Noche",
    description: "Pizarra noche.",
    colors: {
      ink: "#f7fafc",
      muted: "#a0aec0",
      surface: "#0f1420",
      surfaceAlt: "#1a202c",
      brand: "#8aa0b8",
      brandDark: "#5a6d8a",
      accent: "#c9d1e0",
    },
  },
  "amber-dark": {
    label: "Ámbar Noche",
    description: "Ámbar noche.",
    colors: {
      ink: "#fffbeb",
      muted: "#f5d547",
      surface: "#1a1600",
      surfaceAlt: "#2e240a",
      brand: "#f59e0b",
      brandDark: "#d97706",
      accent: "#fbbf24",
    },
  },
  "olive-dark": {
    label: "Oliva Noche",
    description: "Oliva noche.",
    colors: {
      ink: "#f7f5f0",
      muted: "#a8b89a",
      surface: "#0f1a0a",
      surfaceAlt: "#1f2e1a",
      brand: "#8a9a5a",
      brandDark: "#5a7a2e",
      accent: "#b8c99a",
    },
  },
  "berry-dark": {
    label: "Berry Noche",
    description: "Berry noche.",
    colors: {
      ink: "#fdf2f5",
      muted: "#d69ab0",
      surface: "#1a0a0f",
      surfaceAlt: "#2e121a",
      brand: "#e85d8a",
      brandDark: "#9b2e4a",
      accent: "#f0a0c0",
    },
  },
  "sky-dark": {
    label: "Cielo Noche",
    description: "Cielo noche.",
    colors: {
      ink: "#f0f7ff",
      muted: "#94c0e0",
      surface: "#0a1428",
      surfaceAlt: "#0f1f3a",
      brand: "#38bdf8",
      brandDark: "#1e5a8a",
      accent: "#7dd3fc",
    },
  },
  "mint-dark": {
    label: "Menta Noche",
    description: "Menta noche.",
    colors: {
      ink: "#f0fdf4",
      muted: "#86d6a0",
      surface: "#0a1f14",
      surfaceAlt: "#0f2e1f",
      brand: "#22c55e",
      brandDark: "#0e7a4a",
      accent: "#86efac",
    },
  },
  "lavender-dark": {
    label: "Lavanda Noche",
    description: "Lavanda noche.",
    colors: {
      ink: "#f5f3ff",
      muted: "#c9b8e0",
      surface: "#0f0a1f",
      surfaceAlt: "#1e1a2e",
      brand: "#8b5cf6",
      brandDark: "#5a3d8b",
      accent: "#c4b5fd",
    },
  },
  "charcoal-dark": {
    label: "Carbón Noche",
    description: "Carbón noche.",
    colors: {
      ink: "#fafafa",
      muted: "#a0a0a0",
      surface: "#0a0a0a",
      surfaceAlt: "#171717",
      brand: "#e5e5e5",
      brandDark: "#a3a3a3",
      accent: "#737373",
    },
  },
  "sandstone-dark": {
    label: "Arenisca Noche",
    description: "Arenisca noche.",
    colors: {
      ink: "#fdf8f0",
      muted: "#c9b8a0",
      surface: "#1a1208",
      surfaceAlt: "#2e241a",
      brand: "#c9a86a",
      brandDark: "#8b6a3d",
      accent: "#e8c9a8",
    },
  },
  "clay-dark": {
    label: "Arcilla Noche",
    description: "Arcilla noche.",
    colors: {
      ink: "#fdf6f0",
      muted: "#c9a99a",
      surface: "#1a0f0a",
      surfaceAlt: "#2e1e14",
      brand: "#e8a87c",
      brandDark: "#b56a3c",
      accent: "#f5c9a8",
    },
  },
  "moss-dark": {
    label: "Musgo Noche",
    description: "Musgo noche.",
    colors: {
      ink: "#f5f7f5",
      muted: "#a8b5a8",
      surface: "#0a1a0a",
      surfaceAlt: "#1a2e1a",
      brand: "#7a9a5a",
      brandDark: "#3d5a3d",
      accent: "#a8c69f",
    },
  },
  "dusk-dark": {
    label: "Anochecer Noche",
    description: "Anochecer noche.",
    colors: {
      ink: "#f9f5ff",
      muted: "#c9b8d0",
      surface: "#0f0a1f",
      surfaceAlt: "#1e1a2e",
      brand: "#c49ac6",
      brandDark: "#7a5a8a",
      accent: "#e8c4e6",
    },
  },
  "pepper-dark": {
    label: "Pimienta Noche",
    description: "Pimienta noche.",
    colors: {
      ink: "#fdf8f0",
      muted: "#c9a99a",
      surface: "#0f0a08",
      surfaceAlt: "#1f1410",
      brand: "#ff6b35",
      brandDark: "#7a2e1e",
      accent: "#ff8c61",
    },
  },
  "honey-dark": {
    label: "Miel Noche",
    description: "Miel noche.",
    colors: {
      ink: "#fffbeb",
      muted: "#e8d5a0",
      surface: "#1a1200",
      surfaceAlt: "#2e2410",
      brand: "#f5d547",
      brandDark: "#b5892e",
      accent: "#ffe066",
    },
  },

  "sage-pastel": {
    label: "Salvia Pastel",
    description: "Salvia polvo — pastel orgánico.",
    colors: {
      ink: "#2b2e2e",
      muted: "#7a8a85",
      surface: "#fdfdf9",
      surfaceAlt: "#eef4ee",
      brand: "#9bb8a3",
      brandDark: "#7da088",
      accent: "#d9c5b2",
    },
  },
  "mint-pastel": {
    label: "Menta Pastel",
    description: "Menta bruma pastel.",
    colors: {
      ink: "#2b2e2e",
      muted: "#7a8a8a",
      surface: "#fdfefc",
      surfaceAlt: "#e8f5ee",
      brand: "#9ad0b0",
      brandDark: "#7ab89a",
      accent: "#f0d9a8",
    },
  },
  "lavender-pastel": {
    label: "Lavanda Pastel",
    description: "Lavanda niebla pastel.",
    colors: {
      ink: "#2b2a33",
      muted: "#8a7a9a",
      surface: "#fefcff",
      surfaceAlt: "#f1ecff",
      brand: "#b9a8d9",
      brandDark: "#9a8ac0",
      accent: "#ffd6d0",
    },
  },
  "sky-pastel": {
    label: "Cielo Pastel",
    description: "Cielo bruma pastel.",
    colors: {
      ink: "#2b2e33",
      muted: "#7a8a9a",
      surface: "#fcfdff",
      surfaceAlt: "#eaf2ff",
      brand: "#9fc2e8",
      brandDark: "#7aa8d0",
      accent: "#ffe4a8",
    },
  },
  "peach-pastel": {
    label: "Melocotón Pastel",
    description: "Melocotón pastel.",
    colors: {
      ink: "#2b1e14",
      muted: "#8a7a6a",
      surface: "#fffaf7",
      surfaceAlt: "#ffe9e0",
      brand: "#e8a896",
      brandDark: "#d08a6a",
      accent: "#a8d0e0",
    },
  },
  "butter-pastel": {
    label: "Mantequilla Pastel",
    description: "Mantequilla pastel.",
    colors: {
      ink: "#2b2e1a",
      muted: "#8a7a6a",
      surface: "#fffef5",
      surfaceAlt: "#fff5d6",
      brand: "#e6c98a",
      brandDark: "#c9a86a",
      accent: "#b8d4c8",
    },
  },
  "rose-pastel": {
    label: "Rosa Pastel",
    description: "Rosa polvo pastel.",
    colors: {
      ink: "#2e1a22",
      muted: "#9a7a8a",
      surface: "#fff7f9",
      surfaceAlt: "#fbeaf0",
      brand: "#d4a0b0",
      brandDark: "#b87a8a",
      accent: "#c8d8e8",
    },
  },
  "clay-pastel": {
    label: "Arcilla Pastel",
    description: "Arcilla claire pastel.",
    colors: {
      ink: "#2b1e14",
      muted: "#8a7a6a",
      surface: "#fff9f5",
      surfaceAlt: "#f5e6dc",
      brand: "#d2a98f",
      brandDark: "#b88a6a",
      accent: "#9ec8b8",
    },
  },
  "sand-pastel": {
    label: "Arena Pastel",
    description: "Arena niebla pastel.",
    colors: {
      ink: "#2e2a22",
      muted: "#8a7a6a",
      surface: "#fdfcfa",
      surfaceAlt: "#f5ebe2",
      brand: "#c9b8a0",
      brandDark: "#a89a7a",
      accent: "#a9c5b8",
    },
  },
  "dusk-pastel": {
    label: "Anochecer Pastel",
    description: "Anochecer niebla pastel.",
    colors: {
      ink: "#2b2a33",
      muted: "#9a8a9a",
      surface: "#fefcff",
      surfaceAlt: "#f1ecff",
      brand: "#b8a8c8",
      brandDark: "#9a8ab0",
      accent: "#ffdcc5",
    },
  },
  "teal-pastel": {
    label: "Teal Pastel",
    description: "Teal bruma pastel.",
    colors: {
      ink: "#2b2e2e",
      muted: "#7a8a8a",
      surface: "#fcfdfd",
      surfaceAlt: "#e6f0f0",
      brand: "#8fc4c2",
      brandDark: "#6aa8a6",
      accent: "#f5d6b8",
    },
  },
  "moss-pastel": {
    label: "Musgo Pastel",
    description: "Musgo bruma pastel.",
    colors: {
      ink: "#2b2e2b",
      muted: "#7a8a7a",
      surface: "#fcfcfa",
      surfaceAlt: "#eef2eb",
      brand: "#a8b89a",
      brandDark: "#8a9a7a",
      accent: "#e8c9a8",
    },
  },
  "slate-pastel": {
    label: "Pizarra Pastel",
    description: "Pizarra niebla pastel.",
    colors: {
      ink: "#2b2e33",
      muted: "#8a8a9a",
      surface: "#fcfcfc",
      surfaceAlt: "#eef1f5",
      brand: "#a8b0c0",
      brandDark: "#8a90a0",
      accent: "#ffd8a8",
    },
  },
  "indigo-pastel": {
    label: "Índigo Pastel",
    description: "Índigo niebla pastel.",
    colors: {
      ink: "#2b2a33",
      muted: "#8a7a9a",
      surface: "#fcfcff",
      surfaceAlt: "#eceaff",
      brand: "#a8a4d8",
      brandDark: "#8a86c0",
      accent: "#ffe0b8",
    },
  },
  "strawberry-pastel": {
    label: "Fresa Pastel",
    description: "Fresa claire pastel.",
    colors: {
      ink: "#2e1a22",
      muted: "#9a7a8a",
      surface: "#fff8fa",
      surfaceAlt: "#fbeaf0",
      brand: "#d9a8b8",
      brandDark: "#b88a9a",
      accent: "#c5e8d5",
    },
  },
});

export const CUSTOM_COLOR_KEYS = Object.freeze([
  "ink",
  "muted",
  "surface",
  "surfaceAlt",
  "brand",
  "brandDark",
  "accent",
]);

export function isValidPalette(value) {
  return PALETTES.includes(value);
}

export function getPaletteColors(paletteId) {
  return PALETTE_DEFINITIONS[paletteId]?.colors ?? null;
}

export function isHexColor(value) {
  return typeof value === "string" && /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(value.trim());
}

export function resolvePaletteColors(theme) {
  if (!theme) return null;
  if (theme.palette === "custom") {
    if (!theme.colors) return null;
    const missing = CUSTOM_COLOR_KEYS.filter((k) => !isHexColor(theme.colors[k]));
    if (missing.length) return null;
    return {
      ink: theme.colors.ink,
      muted: theme.colors.muted,
      surface: theme.colors.surface,
      surfaceAlt: theme.colors.surfaceAlt,
      brand: theme.colors.brand,
      brandDark: theme.colors.brandDark,
      accent: theme.colors.accent,
    };
  }
  return getPaletteColors(theme.palette);
}
